import Link from "next/link";
import "./globals.css";

interface metadata {
  title: string;
  description: string;
}

export const metadata = {
  title: "TypeX",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}

        <nav className="nav-bar">
          <Link className="routes" href="/contacts">
            Home/Back
          </Link>
        </nav>
      </body>
    </html>
  );
}
